apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: open-webui
  repo: https://helm.openwebui.com
  releaseName: open-webui
  namespace: open-webui
  valuesFile: my-values.yaml
