apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwebui-tls-certificate
  namespace: open-webui
spec:
  secretName: openwebui-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - ai.ghostfrnd.co
